const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'shirts',
      images: '/images/shirts1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 20,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      images: '/images/shirts2.jpg',
      price: 70,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 20,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Free Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      images: '/images/shirts3.jpg',
      price: 70,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 20,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'shirts',
      images: '/images/pants1.jpg',
      price: 70,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 20,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Shirts',
      images: '/images/pants2.jpg',
      price: 70,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 20,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Shirts',
      images: '/images/pants3.jpg',
      price: 70,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 20,
      countInStock: 20,
      description: 'A popular shirt',
    },
  ],
}

export default data
